services:
  db:
    container_name: postgres_container
    image: postgres:17.4-bullseye
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT_EXTERNAL}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
  db_setup:
    image: ghcr.io/jackc/tern:v2.3.2
    restart: no
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./database/migrations/:/db/
    entrypoint:
      [
        "/tern",
        "migrate",
        "--migrations",
        "/db/",
        "--conn-string",
        "postgres://${POSTGRES_USER}:${POSTGRES_PWD}@${POSTGRES_HOST}:${POSTGRES_PORT_EXTERNAL}/${POSTGRES_DB}?sslmode=disable",
      ]
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PWD}
    ports:
      - "${PGADMIN_PORT_EXTERNAL}:${PGADMIN_PORT}"
