services:
  db:
    container_name: postgres_container
    image: postgres:17.4-bullseye
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mfg
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
  # db_migration:
  #   image: ghcr.io/jackc/tern:v2.3.2
  #   restart: no
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   volumes:
  #     - ./database/migrations/:/db/
  #   entrypoint:
  #     [
  #       "/tern",
  #       "migrate",
  #       "--migrations",
  #       "/db/",
  #       "--conn-string",
  #       "postgres://root:root@localhost:5432/mfg?sslmode=disable",
  #     ]
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
