
TRUNCATE TABLE public.order CASCADE;
TRUNCATE TABLE public.board CASCADE;
TRUNCATE TABLE public.line CASCADE;
TRUNCATE TABLE public.job CASCADE;
TRUNCATE TABLE public.feeder CASCADE;
TRUNCATE TABLE public.cart CASCADE;
TRUNCATE TABLE public.machine CASCADE;
TRUNCATE TABLE public.package CASCADE;
TRUNCATE TABLE public.auth CASCADE; 
TRUNCATE TABLE public.user;
TRUNCATE TABLE public.line_job; 
TRUNCATE TABLE public.order_job;


